[package]
name = "harmony_modloader_api"
description = "API for communicating with Harmony ModLoader. This is used by the modloader itself and the browser."
version = "0.0.0"
edition = "2021"

[dependencies]
bitcode = { version = "0", features = ["derive"] }
