[workspace]
resolver = "2"
members = [
    "browser",
    "crates/*",
    "crates/bevy_harmonize/api",
    "crates/bevy_harmonize/build",
    "crates/bevy_harmonize/common",
    "mods/*",
]

# Enable small optimizations for local code
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3
