[package]
name = "the_cube_spinner"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
harmony_modding = { path = "../../crates/modding" }

# Define mod imports here
the_cube = { path = "../the_cube" }
